<div>
    @switch($page)
        @case('index')
            @include('livewire.users.index')
            @break
        @case('create')
        @case('edit')
            @include('livewire.users.create-edit')
            @break
    @endswitch
</div>
